name: moemen
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  adhan_dart: ^1.1.2
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  font_awesome_flutter: ^10.8.0
  fluentui_system_icons: ^1.1.273
  geolocator: ^13.0.2
  http: ^1.3.0
  provider: ^6.1.4
  url_launcher: ^6.3.1
  flutter_svg: ^2.1.0
  build_runner: ^2.4.15
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  get_it: ^8.0.3
  easy_localization: ^3.0.7+1
  flutter_phoenix: ^1.1.1
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  flutter_screenutil: ^5.9.3
  conditional_builder_null_safety: ^0.0.6
  json_serializable: ^6.9.0
  json_annotation: ^4.9.0
  floor: ^1.5.0
  floor_generator: ^1.5.0
  sqlite3_flutter_libs: ^0.5.32
  retrofit: ^4.4.2
  retrofit_generator: ^9.1.9
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  internet_connection_checker:
  internet_connection_checker_plus: ^2.7.1
  location: ^8.0.0
  geocoding: ^3.0.0
  google_fonts:
  sqflite: ^2.4.2
  pay: ^3.2.1
  in_app_purchase: ^3.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_popup: ^3.3.4
  popover: ^0.3.1
  flutter_qiblah: ^3.1.0+1
  google_maps_flutter: ^2.12.1
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  awesome_notifications: ^0.10.1
  purchases_flutter: ^8.7.4
  flutter_timezone: ^4.1.0
  timezone: ^0.10.0
  permission_handler: ^12.0.0+1
  share_plus: ^11.0.0
  in_app_review: ^2.0.10
  get: ^4.7.2
  onepref: ^0.0.19



flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/quran/
    - assets/json/
    - assets/translations/







  fonts:
    - family: ElMessiri
      fonts:
        - asset: assets/fonts/ElMessiri-Bold.ttf
          weight: 700
        - asset: assets/fonts/ElMessiri-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/ElMessiri-Medium.ttf
          weight: 500
        - asset: assets/fonts/ElMessiri-Regular.ttf
          weight: 400
    - family: UthmanTN
      fonts:
        - asset: assets/fonts/UthmanTNB.ttf
          weight: 700
        - asset: assets/fonts/UthmanTN.ttf
          weight: 400
    - family: me_quran
      fonts:
        - asset: assets/fonts/me_quran.ttf
    - family: Hafs
      fonts:
        - asset: assets/fonts/Hafs.ttf
    - family: momen
      fonts:
        - asset: assets/fonts/NotoKufiArabic-Black.ttf
          weight: 100
        - asset: assets/fonts/NotoKufiArabic-Bold.ttf
          weight: 200
        - asset: assets/fonts/NotoKufiArabic-ExtraBold.ttf
          weight: 300
        - asset: assets/fonts/NotoKufiArabic-ExtraLight.ttf
          weight: 400
        - asset: assets/fonts/NotoKufiArabic-Light.ttf
          weight: 500
        - asset: assets/fonts/NotoKufiArabic-Medium.ttf
          weight: 600
        - asset: assets/fonts/NotoKufiArabic-Regular.ttf
          weight: 700
        - asset: assets/fonts/NotoKufiArabic-SemiBold.ttf
          weight: 800
        - asset: assets/fonts/NotoKufiArabic-Thin.ttf
          weight: 900
    - family: Quran
      fonts:
        - asset: assets/fonts/NotoNaskhArabic-Bold.ttf
          weight: 100
        - asset: assets/fonts/NotoNaskhArabic-Medium.ttf
          weight: 200
        - asset: assets/fonts/NotoNaskhArabic-Regular.ttf
          weight: 300
        - asset: assets/fonts/NotoNaskhArabic-SemiBold.ttf
          weight: 400


